#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t agmipagg \
                                                         -C "start_jupyter -A -T @tool notebook.ipynb" \
                                                         -u anaconda-7 \
                                                         -w headless \
                                                         -r none
